- name: "Ansi Install packages"
  become: yes
  yum:
    update_cache: yes
    state: latest

- name: "pull nodejs12 artifacts"
  become: yes
  shell:
    "curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -"
  args:
    chdir: "~/"

- name: "install dependencies"
  become: yes
  yum:
    name: "nodejs"
    state: latest
    update_cache: true

- name: "create ~/web"
  ansible.builtin.file:
    path: ~/web
    state: directory
    mode: '0755'

- name: "copy all files"
  become: yes
  copy:
    src: "{{ role_path }}/files/"
    dest: ~/web/
    mode: "0755"
    backup: yes

- name: "install pm2"
  become: yes
  npm:
    name: "pm2"
    global: true
    production: true
    state: latest


- name: "install dep"
  become: yes
  shell:
    "npm install"
  args:
    chdir: ~/web/

- name: "run app"
  become: yes
  shell:
    "pm2 start index.js -f"
  args:
    chdir: ~/web/