- name: 'update and upgrade packages.'
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
- name: remove unneeded deps
  become: yes
  apt:
    autoremove: yes

- name: install rsync on local
  become: yes
  connection: local
  apt:
    name: ['rsync']
    state: present
 
- name: install rsync on remote
  become: yes
  shell: |
    "apt install -y rsync"
    "whereis rsync"
    "which rsync"

- name: install deps
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

- name: install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes