- name: "copy all files"
  become: yes
  copy:
    src: "~/{{ role_path }}/files/dist/"
    dest: ~/
    mode: "0755"
    backup: yes

- name: "install dep"
  become: yes
  shell: |
    "npm install"
    "pm2 stop default"
    "pm2 start npm -- start"