# - name: "copy all files"
#   become: yes
#   copy:
#     src: "dist/"
#     dest: ~/
#     mode: "0755"
#     backup: yes

# - name: "pull python 2"
#   become: yes
#   shell: |
#     "curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py"
#     "python get-pip.py"
#   args:
#     chdir: "~/"

# - name: "install rsync on remote"
#   yum:
#     name: "rsync"
#     state: latest
#     update_cache: true

- name: "copy files"
  become: yes
  synchronize:
    src: "dist/"
    dest: ~/
    recursive: true
  register: command_output

- debug: 
    var: command_output.stdout_lines

- name: "install dep"
  become: yes
  shell: |
    "npm install"
    "pm2 stop default"
    "pm2 start npm -- start"
  args:
    chdir: ~/dist/
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR: "./migrations"
    TYPEORM_MIGRATIONS: "./migrations/*.js"
    TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"